name: build-and-bump

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      images:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image: ${{ fromJSON(inputs.images) }}
    steps:
      - run: echo "${{ matrix.image.name }}"
