name: build-and-bump

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      images:
        required: true
        type: string
      manifest_dir:
        required: false
        type: string
        default: ""
      manifest_repo:
        required: false
        type: string
        default: "gitupcourt/homelab"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "app_name=${{ inputs.app_name }}"
          echo "manifest_dir=${{ inputs.manifest_dir }}"
          echo "images=${{ inputs.images }}"
